### ISSUE TITLE
Add-on management commands

### ISSUE THREAD

**Issue by kickdev** [xenforo-ltd/docs#18]
Since beta 3, it's obsolete since when installing the add-on, we get the following message:
> Not enough arguments (missing: "step").

**Comment by chrisdeeming** [comment]
The add-on management commands are listed here:
https://xf2demo.xenforo.com/dev-docs/#add-on-management-commands

These commands are general admin-level commands which are used for installing, upgrading or uninstalling an add-on. They have not changed since they were added. They all only accept a single argument, which is the add-on ID.

I think you may be talking about these commands:
https://xf2demo.xenforo.com/dev-docs/development-tools/#run-a-specific-setup-step

These commands are new in Beta 3 and the documentation has been updated accordingly.

**Comment by kickdev** [comment]
No
![default](https://user-images.githubusercontent.com/10669667/30647446-1b90a0e4-9e24-11e7-8845-d8b963704854.PNG)

**Comment by chrisdeeming** [comment]
That's not the correct command to install an add-on.

The correct command to install an add-on is:
```xf:addon-install```

**Comment by kickdev** [comment]
What? The same command is entered, on a screen this is reflected and at input of simply command
![default](https://user-images.githubusercontent.com/10669667/30647813-1e7cc034-9e25-11e7-9e69-a73bcd36fde9.PNG)

**Comment by kickdev** [comment]
My bad, sorry

**Comment by chrisdeeming** [comment]
Easy mistake to make.

We've just discovered that it's possible to set command aliases so from Beta 4 onwards you will be able to use `xf-addon:install` and it will work correctly 😄

**Comment by kickdev** [comment]
Just the habit of writing always and the add-on is activated, and then forgot and entered exactly the same. Thank you, excellent work is waiting for the fourth beta
